services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alquilervehiculos_app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alquilervehiculos
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - alquiler_network
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: alquilervehiculos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alquilervehiculos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - alquiler_network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  alquiler_network:
    driver: bridge
